import { Inter, Roboto, Geist_Mono } from "next/font/google";
import ThemeInitializer from "@/components/ThemeInitializer";
import MockBackendInitializer from "@/components/MockBackendInitializer";
import { DialogProvider } from "@/components/ui/DialogProvider";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <DialogProvider>
          <MockBackendInitializer />
          <ThemeInitializer />
          {children}
        </DialogProvider>
      </body>
    </html>
  );
}
